### PR TITLE
Rename README.txt to README.rst

### PR DESCRIPTION
**Pull request by ChrisBarker-NOAA**
Changing the extension to .rst will let gitHub format it in a more pretty way :)

### CODE REVIEW

**Comment by socolofs** [comment]
Thanks.  I noticed I have some errors on my side that I need to resolve before I post this.  I’ll update that next time I update TAMOC.
-scott

-----------
Scott A. Socolofsky, Professor,
Zachry Department of Civil Engineering
Texas A&M University
(979) 845-4517<tel:%28979%29%20845-4517>

http://ceprofs.civil.tamu.edu/ssocolofsky<https://urldefense.proofpoint.com/v2/url?u=http-3A__ceprofs.civil.tamu.edu_ssocolofsky&d=AwMFEA&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=8wm6_GHJ4KZxKiMISGzENHi_qeZl90A74IFSjD1DqJw&m=0a7PhkcxvZ36f_x92lo6hJEbsOoNUMHpjd6iLpeDpGQ&s=rVXzWL92LnkBQgFNW0vO9hJP06cguOVYA_3alcsThko&e=>
-----------

On Feb 28, 2017, at 7:24 PM, Chris Barker <notifications@github.com<mailto:notifications@github.com>> wrote:


Changing the extension to .rst will let gitHub format it in a more pretty way :)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/socolofs/tamoc/pull/2<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_socolofs_tamoc_pull_2&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=wI57LNnH_J_n5ih_bew7tjq7gaA1a-3-lkx-aTe-Kz0&m=JvipTzOiN_FCm86WO1ZgzDu6htz0phzHUjQl4tGuf1Y&s=ryyqItkz7zfNSDXJmR3DeySrfLBNpWwa-3yQ86yRFsg&e=>

Commit Summary

  *   Rename README.txt to README.rst

File Changes

  *   R README.rst<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_socolofs_tamoc_pull_2_files-23diff-2D0&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=wI57LNnH_J_n5ih_bew7tjq7gaA1a-3-lkx-aTe-Kz0&m=JvipTzOiN_FCm86WO1ZgzDu6htz0phzHUjQl4tGuf1Y&s=urX45-a7pn37sf-5FBdIrKfTTS6xGPCdtXLIAB7B4Q4&e=> (2)

Patch Links:

  *   https://github.com/socolofs/tamoc/pull/2.patch<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_socolofs_tamoc_pull_2.patch&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=wI57LNnH_J_n5ih_bew7tjq7gaA1a-3-lkx-aTe-Kz0&m=JvipTzOiN_FCm86WO1ZgzDu6htz0phzHUjQl4tGuf1Y&s=LQrP05BySZKQg3pIPaL5Hyvdd7j6q830vRXYwxWdLug&e=>
  *   https://github.com/socolofs/tamoc/pull/2.diff<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_socolofs_tamoc_pull_2.diff&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=wI57LNnH_J_n5ih_bew7tjq7gaA1a-3-lkx-aTe-Kz0&m=JvipTzOiN_FCm86WO1ZgzDu6htz0phzHUjQl4tGuf1Y&s=h1KzCozYoodMS_rdo36yY-CXW48E3G3--wGOFtCQdMk&e=>

**Comment by ChrisBarker-NOAA** [comment]
it actually looked pretty good rendered to me.

Or maybe you mean content updates. Anyway, no biggie.

**Comment by socolofs** [comment]
I mean that I have a couple of file conflicts before I synchronize the whole package.  I could update just the readme file.  Maybe I should do that.

-Scott

-----------
Scott A. Socolofsky, Professor,
Zachry Department of Civil Engineering
Texas A&M University
(979) 845-4517<tel:%28979%29%20845-4517>

http://ceprofs.civil.tamu.edu/ssocolofsky<https://urldefense.proofpoint.com/v2/url?u=http-3A__ceprofs.civil.tamu.edu_ssocolofsky&d=AwMFEA&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=8wm6_GHJ4KZxKiMISGzENHi_qeZl90A74IFSjD1DqJw&m=0a7PhkcxvZ36f_x92lo6hJEbsOoNUMHpjd6iLpeDpGQ&s=rVXzWL92LnkBQgFNW0vO9hJP06cguOVYA_3alcsThko&e=>
-----------

On Mar 1, 2017, at 1:24 PM, Chris Barker <notifications@github.com<mailto:notifications@github.com>> wrote:


it actually looked pretty good rendered to me.

Or maybe you mean content updates. Anyway, no biggie.

**Comment by ChrisBarker-NOAA** [comment]
I see this now has conflicts -- I'll just close it.

**Comment by ChrisBarker-NOAA** [comment]
And the change was made anyway :-)

**Pull request closed without merging**
